plugins {
    id 'com.android.application'
}

apply from: '../depends.gradle'

android {
    namespace 'com.xd.xdmanager'
    defaultConfig {
        applicationId "com.xd.xdmanager"
        versionCode VER_CODE
        versionName VER_NAME
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    android.applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def outputFile = output.outputFile
            def targetFileNamePrefix
            def formattedData = new Date().format('yyyyMMddHHmm', TimeZone.getTimeZone("GMT+08"))
            def fileNamePrefix = "${project.name}-${variant.baseName}"
            project.logger.error("fileNamePrefix: ${fileNamePrefix}")

            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                project.logger.error("outputFile: ${outputFile}")

                if (variant.buildType.name == "release") {
                    targetFileNamePrefix = "XDManager_V${project.android.defaultConfig.versionCode}_${project.android.defaultConfig.versionName}_${variant.productFlavors.name}_release_${formattedData}"
                } else if (variant.buildType.name == "debug") {
                    targetFileNamePrefix = "XDManager_V${project.android.defaultConfig.versionCode}_${project.android.defaultConfig.versionName}_${variant.productFlavors.name}_debug_${formattedData}"
                }
                outputFileName = "${targetFileNamePrefix}.apk"
                project.logger.error("outputFileName: ${targetFileNamePrefix}")
            }
        }
    }
}

dependencies {

    implementation 'io.moquette:moquette-broker:0.15'
    implementation 'androidx.lifecycle:lifecycle-service:2.5.1'

    implementation 'org.webrtc:google-webrtc:1.0.+'
    implementation "org.java-websocket:Java-WebSocket:1.4.0"

    implementation project(path: ':lib_can')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'androidx.activity:activity:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

}