boolean isApplication = MODULE_APPLICATION_CAN
if (isApplication) {
    apply plugin: 'com.android.application'
} else {
    apply plugin: 'com.android.library'
}

apply from: '../depends.gradle'

android {
    namespace 'com.xd.lib_can'
    defaultConfig {
        versionCode VER_CODE
        versionName VER_NAME
        if (isApplication) {
            applicationId "com.xd.lib_can"
        }

        externalNativeBuild {
            cmake {
                cppFlags ''
            }
        }
    }
    sourceSets {
        main {
            if (!isApplication) {
                manifest.srcFile 'src/main/AndroidManifest.xml'
            } else {
                manifest.srcFile 'src/main/app/AndroidManifest.xml'
            }
        }
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.18.1'
        }
    }
}